# Site wide configuration

title:            Sukhdeep Singh &#58 Bioinformatician, DJ and an Adventurer
locale:           en_GB
url:              http://sukhdeepsingh.eu


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Sukhdeep Singh
  avatar: sukhiBio.jpg
  bio: "Bioinformatician, DJ and an Adventurer! I love travelling, hiking, making friends & frisbee."
  email: sukhdeepsingh.bio@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: vanbug
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# image cropping via MiniMagick, setting up presets
mini_magick:
    thumbnail:
        source: images/
        destination: images/magick/thumbnail
        resize: "100x100"
    medium:
        source: images/
        destination: images/magick/medium
        resize: "600x400"
    cover:
        source: images/
        destination: images/magick/cover
        resize: "851x315"
    

