# Site wide configuration

title:            Sukhdeep Singh &#58 Bioinformatician, DJ and an Adventurer
locale:           en_GB
url:              http://localhost:4000
#http://localhost:4000
#http://sukhdeepsingh.eu
#
#

# resume links
favicon: sukhiBio.jpg

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-minimagick # same name as given in the gem file

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Sukhdeep Singh
  avatar: sukhiBio.jpg
  bio: "I love travelling, hiking, frisbee and making friends."
  email: sukhdeepsingh.bio@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: sukhdeepsingh
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: pub/sukhdeep-singh/7/a79/a5b
  xing: #username
  instagram: vanbug
  lastfm: #username
  tumblr: cruisingwarrior
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: UCcj1tSCvFu15-WRiK15uz_w
  soundcloud: nordic-berry
  biostars: u/426/
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# image cropping via MiniMagick, setting up presets, adding ! sign to the end of size, unlocks the aspect ratio
mini_magick:
    thumbnail:
        source: images
        destination: images/thumbnails
        resize: "100x100"
        #commands:
        #- thumbnail: "140x140^"
        #- crop: "140x140-0x0"
    medium:
        source: images/
        destination: images/medium
        resize: "600x400"
    cover:
        source: images/
        destination: images/cover
        resize: "1500X250!"

#mini_magick:
#  thumbnail:
#    source: gallery
#    destination: thumbnails
#    commands:
#      - thumbnail: "140x140^"
#      - crop: "140x140-0x0"
#  catnail:
#    source: cats
#    destination: cats/thumbs
#    commands:
#      - thumbnail: "140x140^"
#      - crop: "140x140-0x0"





# Resume Data
# Author settings
author:
  name: <a href='http://sukhdeepsingh.eu'>Sukhdeep Singh</a>
  title: Bioinformatician
  address: Biotechnologisches Zentrum, Dresden, Germany
  email: sukhdeepsingh.bio@gmail.com
  link: http://sukhdeepsingh.eu
  weibo:
  github: sukhdeepsingh
  linkedin: pub/sukhdeep-singh/7/a79/a5b
  twitter: 
  gavatar: /assests/img/sukhiBio.jpg
  workHistory:
    - work1:
      company: Biotec TU Dresden
      location: Dresden, Germany
      title: Predoctoral Student.
      started: 2011
      duration: July 2011 – Present
      description: I am a pre-doctoral student and a bio-informatician by background working with high-throughput transcriptomic and regulomic (ChIP-Seq,RNA-SEQ) data to understand the interplay of histone methylases and demethylases in the mouse embryonic stem cell development. Our lab (Francis Stewart) is a core epigenetics lab and I support the bioinformatics component of the de-centralized experimental network of the SYBOSS project. http://www.syboss.eu/
    - work2:
      company: SYBOSS Project Systems Biology of Stem Cells and Reprogramming.
      location: Dresden, Germany
      title: Bioinformatician.
      started: 2011
      duration: July 2011 – Present
      description: Creating ChIP-Seq and RNA-Seq computational pipelines for handling and analysis of data-sets generated within project from home and the partner labs. The aim of the project is to understand how a simple stem cell becomes a highly specialized member of a network, and how those conditions could be recreated in treating disease.
    - work3:
      company: Biostars.org
      location: Worldwide
      title: Editor
      started: 2013
      duration: January 2013 – Present
      description: "My duties include : 
        - monitoring spam and other content
        - answering, editing and reformatting the posts
        - closing duplicate, less informative and non-related posts"

  educationHistory:
    - education1:
      organization: Northeastern University
      degree: Bachelor
      major: Software Engineering
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: German
      proficiency: Conversational
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Hindi/Punjabi
      proficiency: Native
  programmingSkills:
    - skill1:
      name: ChIP-Seq
      percentage: 100%
    - skill2:
      name: RNA-Seq
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 80%
    - skill4:
      name: AngularJS
      percentage: 80%
    - skill5:
      name: Java/Java EE
      percentage: 90%
